# Generated by Django 3.2.7 on 2021-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('documento', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField()),
                ('compras', models.IntegerField(default=0)),
                ('Ultima_compra', models.DateTimeField()),
            ],
        ),
    ]
